openapi: 3.0.0
info:
  title: Entertainment Web App
  description: Entertainment Web App API
  version: 0.1.9

servers:
  - url: https://entertainment-mongo-production.up.railway.app/api
    description: production server
  - url: http://localhost:5000/api
    description: local server
paths:
  /movies:
    get:
      tags:
        - Movies
      responses:
        "200":
          description: Successfully fetched
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
  /user/profile:
    get:
      tags:
        - Users
      responses:
        "200":
          description: Successfully fetched
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
  /user/register:
    post:
      tags:
        - Users
      requestBody:
        description: create user
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
            example:
              email: test_email@example.com
              password: test123
      responses:
        "200":
          description: user created
  /user/login:
    post:
      tags:
        - Users
      requestBody:
        description: login user
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
            example:
              email: test_email@example.com
              password: test123
      responses:
        "200":
          description: user loggedin
